<?php

return [
    App\Providers\Agricola\CdpServiceProvider::class,
    App\Providers\Agricola\CropInputProvider::class,
    App\Providers\Agricola\CropParameterProvider::class,
    App\Providers\Agricola\CropRangesProvider::class,
    App\Providers\Agricola\CropServiceProvider::class,
    App\Providers\Agricola\CropStepProvider::class,
    App\Providers\Agricola\FincaGroupServiceProvider::class,
    App\Providers\Agricola\FincaServiceProvider::class,
    App\Providers\Agricola\LoteProvider::class,
    App\Providers\Agricola\RecipeProvider::class,
    App\Providers\Agricola\RecipeServiceProvider::class,
    App\Providers\Agricola\SupplyServiceProvider::class,
    App\Providers\Agricola\TaskServiceInterface::class,
    App\Providers\Agricola\TaskServiceProvider::class,
    App\Providers\Agricola\WeeklyPlanEmployeeServiceProvider::class,
    App\Providers\Agricola\WeeklyPlanServiceProvider::class,
    App\Providers\Agricola\WeeklyPlanTaskEmployeeServiceProvider::class,
    App\Providers\Agricola\WeeklyPlanTaskInsumoServiceProvider::class,
    App\Providers\Agricola\WeeklyPlanTaskPartialClosureProvider::class,
    App\Providers\Agricola\WeeklyPlanTaskServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\Auth\AuthProvider::class,
    App\Providers\Permissions\PermissionProvider::class,
    App\Providers\Users\UserProvider::class,
];
